root = "."
tmp_dir = ".tmp"

[build]
  args_bin = []
  bin = "./bin/bot start --start-ipc"
  cmd = "mage build:dev"
  delay = 500
  exclude_dir = ["logs", "bin"]
  exclude_file = ["Dockerfile", "mage_output_file.go"]
  exclude_regex = ["_test\\.go", "\\.null-ls",]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "sql"]
  include_file = []
  kill_delay = "500ms"
  log = "logs/build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
