version: '3.4'

x-common-variables: &common-variables
  SERVICE_RESTART_TIMEOUT: 2
  NODE_ENV: development

services:
  buggins-db:
    image: postgres:15-alpine
    container_name: buggins-db
    environment:
      POSTGRES_PASSWORD: buggins
      POSTGRES_USER: buggins
      POSTGRES_DB: buggins

  buggins-bot:
    container_name: buggins-bot
    stdin_open: true
    tty: true
    build:
      context: .
      args:
        IMAGE_TYPE: development
    image: buggins
    volumes:
      - .:/app
    ports:
      - '127.0.0.1:9240:9230' # remote debugger
    command: /app/docker/api/debug_command.sh
    depends_on:
      - buggins-db
    environment:
      <<: *common-variables

networks:
  default:
    name: buggins
