#!/bin/sh

ARGS=("$@")

if [ "create" = "${ARGS[0]}" ]; then
  migrate \
    -source file://./internal/db/migrations \
    -database sqlite://./data/database.sqlite create \
    -dir ./internal/db/migrations/ \
    -ext sql \
    "${ARGS[1]}"
else
  migrate \
    -source file://./internal/db/migrations \
    -database sqlite://./data/database.sqlite up
fi
