// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: ipc.proto

package ipc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IpcService_ReloadConfiguration_FullMethodName = "/ipc.v1.IpcService/ReloadConfiguration"
)

// IpcServiceClient is the client API for IpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IpcServiceClient interface {
	ReloadConfiguration(ctx context.Context, in *ReloadConfigurationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type ipcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIpcServiceClient(cc grpc.ClientConnInterface) IpcServiceClient {
	return &ipcServiceClient{cc}
}

func (c *ipcServiceClient) ReloadConfiguration(ctx context.Context, in *ReloadConfigurationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IpcService_ReloadConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IpcServiceServer is the server API for IpcService service.
// All implementations must embed UnimplementedIpcServiceServer
// for forward compatibility.
type IpcServiceServer interface {
	ReloadConfiguration(context.Context, *ReloadConfigurationRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedIpcServiceServer()
}

// UnimplementedIpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIpcServiceServer struct{}

func (UnimplementedIpcServiceServer) ReloadConfiguration(context.Context, *ReloadConfigurationRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadConfiguration not implemented")
}
func (UnimplementedIpcServiceServer) mustEmbedUnimplementedIpcServiceServer() {}
func (UnimplementedIpcServiceServer) testEmbeddedByValue()                    {}

// UnsafeIpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IpcServiceServer will
// result in compilation errors.
type UnsafeIpcServiceServer interface {
	mustEmbedUnimplementedIpcServiceServer()
}

func RegisterIpcServiceServer(s grpc.ServiceRegistrar, srv IpcServiceServer) {
	// If the following call pancis, it indicates UnimplementedIpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IpcService_ServiceDesc, srv)
}

func _IpcService_ReloadConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpcServiceServer).ReloadConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IpcService_ReloadConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpcServiceServer).ReloadConfiguration(ctx, req.(*ReloadConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IpcService_ServiceDesc is the grpc.ServiceDesc for IpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ipc.v1.IpcService",
	HandlerType: (*IpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReloadConfiguration",
			Handler:    _IpcService_ReloadConfiguration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ipc.proto",
}
