// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"time"
)

type FeaturedMessage struct {
	GuildID   string    `json:"guild_id"`
	ChannelID string    `json:"channel_id"`
	MessageID string    `json:"message_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ModuleConfiguration struct {
	Module  string      `json:"module"`
	Key     string      `json:"key"`
	Options interface{} `json:"options"`
}

type SeenObservation struct {
	ID        int64     `json:"id"`
	ChannelID string    `json:"channel_id"`
	ProjectID int64     `json:"project_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
