// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package store

import (
	"context"
	"strings"
)

const createSeenObservation = `-- name: CreateSeenObservation :one
insert
  or ignore into seen_observation (id)
    values (?)
  returning
    id, created_at, updated_at
`

func (q *Queries) CreateSeenObservation(ctx context.Context, id int64) (SeenObservation, error) {
	row := q.db.QueryRowContext(ctx, createSeenObservation, id)
	var i SeenObservation
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const findObservationsByIds = `-- name: FindObservationsByIds :many
select
  id, created_at, updated_at
from
  seen_observation
where
  id in (/*SLICE:ids*/?)
`

func (q *Queries) FindObservationsByIds(ctx context.Context, ids []int64) ([]SeenObservation, error) {
	query := findObservationsByIds
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeenObservation
	for rows.Next() {
		var i SeenObservation
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isMessageFeatured = `-- name: IsMessageFeatured :one
select
  exists (
    select
      1
    from
      featured_message
    where
      channel_id = ?
      and message_id = ?
    limit 1)
`

type IsMessageFeaturedParams struct {
	ChannelID string `json:"channel_id"`
	MessageID string `json:"message_id"`
}

func (q *Queries) IsMessageFeatured(ctx context.Context, arg IsMessageFeaturedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isMessageFeatured, arg.ChannelID, arg.MessageID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const saveFeaturedMessage = `-- name: SaveFeaturedMessage :one
insert
  or ignore into featured_message (message_id, channel_id)
    values (?, ?)
  returning
    channel_id, message_id, created_at, updated_at
`

type SaveFeaturedMessageParams struct {
	MessageID string `json:"message_id"`
	ChannelID string `json:"channel_id"`
}

func (q *Queries) SaveFeaturedMessage(ctx context.Context, arg SaveFeaturedMessageParams) (FeaturedMessage, error) {
	row := q.db.QueryRowContext(ctx, saveFeaturedMessage, arg.MessageID, arg.ChannelID)
	var i FeaturedMessage
	err := row.Scan(
		&i.ChannelID,
		&i.MessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
