---
name: Buggins Vulnerability Check

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  vulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Run govulncheck
        run: go tool golang.org/x/vuln/cmd/govulncheck ./...
