name: Lint

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    name: Lint and test
    env:
      DATABASE_URL: postgres://buggins:buggins@localhost:5432/buggins
      NODE_ENV: testing

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: buggins
          POSTGRES_USER: buggins
          POSTGRES_DB: buggins
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name postgres

    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Install musl
        run: sudo apt install -y musl-dev
      - name: Link musl
        run: sudo ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1
      - name: Lint
        run: yarn lint
      - name: Run current migrations for default database
        run: yarn typeorm:cli migration:run
      - name: Check for missing migrations in default database
        run: yarn typeorm:cli migration:generate --ch ./src/databases/migrations/default
